import React from 'react'

function BookPage() {
  return (
    <div className='mainContainer'>
      <div className="flex items-center justify-start UpperContainer h-[370px] w-screen p-10">
        <div className="bookImage">
            <img src="https://i0.wp.com/princetonbuffer.princeton.edu/wp-content/uploads/sites/185/2015/02/The-Hobbit.jpg?resize=672%2C372&ssl=1" alt="" className='h-[300px] w-[450px] object-cover rounded-md'/>
        </div>
      <div className="p-5 bookDetails">
      <h1 className='p-2 text-2xl border-stone-950'>Title : The Hobbit</h1>
      <h1 className='p-2 text-2xl border-y-2 border-stone-950'>Author : Sahil Sharma</h1>
      <h1 className='p-2 text-2xl border-y-2 border-stone-950'>Genre : Fiction</h1>
      <h1 className='p-2 text-2xl border-y-2 border-stone-950'>Date Published : 12/08/2002</h1>
      </div>
      </div>
      <div className="p-5 mb-5 lowerContainer bookContent">
        <p className='p-5 text-lg '>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas expedita amet nostrum aperiam autem, recusandae officiis nobis placeat adipisci corporis iusto, corrupti veritatis distinctio fugiat voluptate reprehenderit perferendis optio ducimus error beatae dolores quo. Veniam rerum iste saepe libero beatae nesciunt iusto iure voluptatum quibusdam ipsam, odit eveniet cupiditate ratione maiores fugiat, deleniti quos eaque earum ab. Ab, quaerat inventore tempora at officiis ipsum ducimus quod debitis quam suscipit dicta voluptatem quibusdam explicabo. Placeat sunt soluta dolorem natus velit, culpa fugit voluptas omnis beatae incidunt amet animi non at explicabo commodi deleniti alias sed nihil, ab unde nisi ut. Blanditiis facere nobis itaque vero ea praesentium neque quis dolores, ut eos, ullam maxime maiores inventore optio error magnam obcaecati magni consequuntur iusto minus deserunt aperiam placeat dolor earum. Expedita, aut atque culpa nobis, ipsa facilis saepe quasi illo quia aspernatur praesentium molestias necessitatibus est suscipit eaque minima consequatur accusantium et. Ipsam aperiam perspiciatis molestias minus nesciunt libero necessitatibus nostrum ullam deleniti. Voluptatibus mollitia ad recusandae, quo voluptates odit ipsum dolorem quas veritatis? Accusamus quasi impedit dolor officia. Maxime veniam incidunt explicabo cupiditate illum placeat recusandae debitis vitae expedita voluptatum similique quae odit, accusantium sapiente! Illum quia eos accusantium commodi ab. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo ducimus maxime debitis blanditiis earum? Natus ducimus necessitatibus error laborum cum dignissimos, velit magnam? Dolores sed minima nesciunt blanditiis, consectetur ipsum soluta animi labore ratione facilis, voluptatem quis qui molestiae illum dolore ducimus omnis facere voluptatum autem, molestias amet alias aliquid esse! In eos culpa repellat reiciendis inventore architecto.
        </p>
        <p className='p-5 text-lg '> incidunt repudiandae quam sit ab similique ratione iure qui saepe possimus quisquam impedit aliquam voluptatum perspiciatis, sapiente asperiores? Consequuntur molestiae ullam iste ad repellat reiciendis inventore maxime! A, ab deleniti velit, voluptas quasi explicabo, illo nemo quisquam ipsum quaerat sint magni debitis praesentium porro magnam enim omnis ratione eveniet doloribus aliquam! Nisi id illo, ea nesciunt nobis veritatis culpa sapiente architecto non alias similique animi quod laudantium ipsum quae distinctio sequi vitae. Officia vel excepturi reiciendis totam iure delectus non ea, quae quidem cum aliquid placeat dolorum eos nobis repellendus voluptas. Provident dignissimos cupiditate vero facere error cum modi quae nulla, exercitationem possimus necessitatibus magnam consequuntur nihil laudantium voluptates corrupti nisi illo vel, incidunt voluptatum odio ut! Esse impedit fuga inventore voluptates nesciunt voluptatibus omnis placeat totam repellat, iste id ipsum ratione pariatur in dolorum. Cupiditate ex facilis optio id suscipit, sapiente vitae earum perferendis! Et architecto quia at asperiores animi eaque ut, optio rerum voluptatum pariatur dolorum a! Consequuntur doloribus illo quisquam illum quam ad ullam maiores dolores pariatur quo iusto consectetur, laboriosam sequi nostrum commodi ut autem? Possimus nobis, sed assumenda laboriosam ipsum veritatis ipsam corrupti? Quo officiis similique magni. Iure tempore odit mollitia ipsa aut voluptate. Dicta dolore quos ratione mollitia inventore ex molestiae possimus unde. Dolores nostrum quae ex libero culpa dicta inventore quo veniam vero quis nisi, a ullam officia voluptates, possimus ducimus, itaque adipisci iusto tempore esse voluptas accusamus sunt molestiae. </p>
        <p className='p-5 text-lg '>Quaerat voluptatem necessitatibus cupiditate modi vero, repellat placeat ratione ea est omnis soluta odit harum fugiat repudiandae in, fuga nostrum itaque eveniet laudantium dolorum veniam unde consectetur totam amet. Labore asperiores quidem explicabo expedita saepe aspernatur incidunt voluptatum ullam ipsam. Quia reiciendis corrupti eligendi vitae minima ullam mollitia labore cumque totam sed fugit ad eum consequuntur earum accusamus, consequatur, voluptatum praesentium assumenda dolore vel blanditiis expedita deleniti veritatis quidem! Doloremque excepturi repellat quasi molestias nemo accusamus, eos vero nulla eius commodi quas consequuntur totam facilis perferendis fuga iste harum sed quis. Adipisci natus expedita placeat architecto. Maxime repellat autem aliquid omnis perferendis iste et veritatis optio est beatae eum, provident tenetur eveniet cupiditate totam quo, mollitia earum pariatur consequuntur sunt iure quod repudiandae maiores. Suscipit nemo hic nobis! Laudantium, quidem expedita excepturi fugiat officia voluptatem dicta libero inventore error sit reprehenderit consequuntur facere at.</p>
        
        <p className='p-5 text-lg' > deleniti quis? Molestias eveniet consequatur doloremque aperiam! Officia commodi minus eius suscipit sit obcaecati nesciunt nulla quo deleniti expedita? Deleniti repellendus velit pariatur. Consequatur aliquam exercitationem est dolorem architecto sunt sit voluptas, fugit magnam, ab fugiat accusamus. Cum temporibus quidem quasi nulla sapiente. Laudantium adipisci sed, id ullam eveniet, accusamus libero perspiciatis, modi hic tempora asperiores aspernatur illum quod nulla ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam vitae est voluptatem unde tempora perspiciatis delectus laudantium cupiditate officia. Tempora earum dolor sunt, iure culpa commodi neque vitae rem magni magnam impedit, distinctio in totam. Et autem consequuntur dicta? Dignissimos pariatur vero doloribus hic sit tenetur architecto quae soluta nobis?</p>
      </div>
    </div>
  )
}

export default BookPage
